version: "3.7"

services:

  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:7.12.1"
    environment:
      discovery.type: "single-node"
      cluster.name: "cluster-1"
      node.name: "node-1"
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"  # Limit memory usage to 1 GB
    ports:
      - "9200:9200"
    volumes:
      - "./tmp/elasticsearch/data:/usr/share/elasticsearch/data"
    deploy:
      resources:
        limits:
          memory: 2g  # Limit Elasticsearch container to 2 GB of RAM

  elastichq:
    image: "elastichq/elasticsearch-hq"
    ports:
      - "5000:5000"
    depends_on:
      - "elasticsearch"

  cerebro:
    image: "lmenezes/cerebro"
    ports:
      - "9000:9000"
    depends_on:
      - "elasticsearch"
